# Backend/model/reporting.py
from fpdf import FPDF
import tempfile

class AquaEyeReport(FPDF):
    def __init__(self, request_id, stats):
        super().__init__()
        self.id = request_id
        self.stats = stats
        self.calibration = 0.65 # microns per pixel
        
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'AquaEye Metrology Station', 0, 1, 'L')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'ISO 16232-10:2007 Compliant Certificate of Analysis', 0, 1, 'L')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Doc ID: {self.id} | Generated by AquaEye Neural Core', 0, 0, 'C')

    def generate(self, raw_path, mask_path, output_path):
        self.add_page()
        
        # 1. ISO Table Logic
        bins = {'B (5-15um)': 0, 'C (15-25um)': 0, 'D (25-50um)': 0, 'E (50-100um)': 0, 'F-K (>100um)': 0}
        for p in self.stats['particles']:
            size = p['major_axis'] * self.calibration
            if 5 <= size < 15: bins['B (5-15um)'] += 1
            elif 15 <= size < 25: bins['C (15-25um)'] += 1
            elif 25 <= size < 50: bins['D (25-50um)'] += 1
            elif 50 <= size < 100: bins['E (50-100um)'] += 1
            elif size >= 100: bins['F-K (>100um)'] += 1

        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, '1. Particle Size Distribution (ISO 16232)', 0, 1)
        
        self.set_font('Arial', 'B', 10)
        self.set_fill_color(240, 240, 240)
        self.cell(60, 10, 'Size Class', 1, 0, 'C', 1)
        self.cell(60, 10, 'Count', 1, 1, 'C', 1)
        
        self.set_font('Arial', '', 10)
        for label, count in bins.items():
            self.cell(60, 10, label, 1, 0)
            self.cell(60, 10, str(count), 1, 1, 'C')
            
        self.ln(10)
        
        # 2. Physics Audit
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, '2. Physics Guardrail Audit', 0, 1)
        self.set_font('Arial', '', 10)
        self.cell(100, 8, f"Total Objects Detected: {self.stats['total_detected']}", 0, 1)
        self.cell(100, 8, f"Rejected (Bubbles): {self.stats['rejected_bubbles']}", 0, 1)
        self.cell(100, 8, f"Rejected (Biofilm): {self.stats['rejected_biofilm']}", 0, 1)
        self.cell(100, 8, f"Accepted Microplastics: {self.stats['accepted_count']}", 0, 1)

        # 3. Images
        self.ln(10)
        self.image(raw_path, x=10, y=140, w=90)
        self.image(mask_path, x=110, y=140, w=90)
        
        self.output(output_path)